# Generated by Django 4.1.7 on 2023-04-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
