# Generated by Django 4.1.7 on 2023-04-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0005_alter_notes_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
